### ISSUE TITLE
Getting error with "index_creator"

### ISSUE THREAD

**Issue by wns-sakshamjai** [mlabonne/how-to-data-science#2]
**In Section:**
text = "Apple announced the Vision Pro in 2023."
index_creator = GraphIndexCreator(llm=OpenAI(temperature=0))
graph = index_creator.from_text(text)
graph.get_triples()

**Facing issue:**
Must provide an 'engine' or 'deployment_id' parameter to create a <class 'openai.api_resources.chat_completion.ChatCompletion'>

**After Debugging** - Added -> engine="gpt-35-turbo" along with Temperature.
Code works but Getting Wrong outputs.

**Comment by mlabonne** [comment]
Hi, the engine is defined in the previous cell block. Have you executed it before the one you're citing?

**Comment by wns-sakshamjai** [comment]
Yes, I have done that.
That's the thing, getting the error of Engine needed even after defining it in the first cell.

Can you try re-running the code, if you get some time please.

**Comment by sakshamjn** [comment]
Found the Issue, Code is perfectly fine.

Reason:- 
Earlier I was using Microsoft's Azure based OpenAI Key, tried using my personal key it worked absolutely right.

Thanks for your support @mlabonne.

**Comment by mlabonne** [comment]
Ok great, I was out of ideas haha
